name       : libgpod
version    : 0.8.3
release    : 4
source     :
    - http://netcologne.dl.sourceforge.net/project/gtkpod/libgpod/libgpod-0.8/libgpod-0.8.3.tar.bz2 : 638a7959d04e95f1e62abad02bd33702e4e8dfef98485ac7d9d50395c37e955d
homepage   : https://sourceforge.net/projects/gtkpod/
license    : LGPL-2.0-or-later
component  : multimedia.library
summary    : libgpod is a shared library to access the contents of an iPod
description: |
    libgpod is a library meant to abstract access to an iPod content. It provides an easy to use API to retrieve the list of files and playlist stored on an iPod, to modify them and to save them back to the iPod.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(glib-sharp-2.0)
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libusb-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - sg3_utils-devel
    - swig
setup      : |
    %patch -p1 < $pkgfiles/libgpod-fixswig.patch
    %patch -p1 < $pkgfiles/0001-configure.ac-Add-support-for-libplist-2.2.patch
    %reconfigure --disable-static \
        --enable-udev \
        --with-python=no \
        --with-udev-dir=/usr/lib/udev/
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    rm -rf $installdir/tmp
