name       : libgpod
version    : 0.8.3
release    : 1
source     :
    - http://netcologne.dl.sourceforge.net/project/gtkpod/libgpod/libgpod-0.8/libgpod-0.8.3.tar.bz2 : 638a7959d04e95f1e62abad02bd33702e4e8dfef98485ac7d9d50395c37e955d
license    : LGPL-2.0
component  : multimedia.library
summary    : libgpod is a shared library to access the contents of an iPod.
description: |
    libgpod is a shared library to access the contents of an iPod.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libusb-1.0)
    - pkgconfig(pygobject-2.0)
    - pkgconfig(python-2.7)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - mutagen
    - swig
rundeps    :
    - mutagen
    - swig
setup      : |
    %patch -p1 < $pkgfiles/libgpod-fixswig.patch
    %configure --disable-static \
        --enable-udev \
        --with-python=/usr/bin/python2 \
        --with-udev-dir=/usr/lib/udev/
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    rm -rf $installdir/tmp
